apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: hello-dotnet
  labels:
    run: hello-dotnet
spec:
  rules:
  - host: http://localhost:4343
    http:
      paths:
      - backend:
          service:
            name: hello-dotnet
            port:
              number: 80
        path: /
        pathType: ImplementationSpecific
