apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: hello-dotnet
  labels:
    run: hello-dotnet
spec:
  rules:
  - http:
      paths:
      - path: /
        backend:
          serviceName: hello-dotnet
          servicePort: 80