apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: hello-dotnet
  labels:
    run: hello-dotnet
spec:
  rules:
  - host: frontend.10.0.0.1.nip.io # IMPORTANT: update <ingress ip> with the dashed public IP of your ingress, for example frontend.13-68-177-68.nip.io
    http:
      paths:
      - backend:
          service:
            name: ratings-web
            port:
              number: 80
        path: /
        pathType: ImplementationSpecific
